### PR TITLE
add sci-hub DOI search function

### PR DESCRIPTION
**Pull request by mde-pach**
I add the management of Sci-hub with your amazing extension.
I hope this will be helpful

### CODE REVIEW

**Comment by jmnicholson** [comment]
Maybe you could make this not so specific to SH but more general?

**Comment by mde-pach** [comment]
Like a "title DOI extraction" function ?

**Comment by jmnicholson** [comment]
Yep!

**Comment by bananaoomarang** [comment]
Apologies, this slipped my mind! Thanks @mde-pach merging this!

**Pull request merged**
